# Generated by Django 5.0.3 on 2024-03-17 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets_Owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameP', models.CharField(max_length=30)),
                ('ageP', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets_Owner.owner')),
            ],
        ),
    ]
